import 'package:oken/constants/types.dart' as TYPES;

List<Map> _content = [
  {
    'title': 'Random quiz',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624481413/u01.jpg',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625883512/quiz01.jpg',
    'type': TYPES.QUESTION,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'questions',
    'question_type': 'random'
  },
  {
    'title': 'Interviews',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624481070/i10.jpg',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625884257/job04.png',
    'type': TYPES.QUESTION,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'questions',
    'question_type': 'interview'
  },
  {
    'title': 'Describe it',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625899452/za08.jpg',    
    'type': TYPES.IMGS_HINT,
    'pack': 'pack_a',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'images',
  },
  {
    'title': 'Dracula - Bram Stoker',
    'author': 'Bram Stoker',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625880702/dra03.png',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625255989/dra01.png',
    'type': TYPES.BOOK,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'reading',
    'hasChapters': true,
    'paginatorIndex': 0,
    'chapterNumber': 1,
    'chapters': [
      {'type': 'bullet', 'selected': true, 'comingSoon': false, 'path': 'dracula_01_01.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_02.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_03.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_04.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_05.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_06.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_07.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'dracula_01_08.json'},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 2', 'path': ''},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 3', 'path': ''},
    ]
  },
  {
    'title': 'The War Of The Worlds',
    'author': 'H. G. Wells',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625880915/worlds01.jpg',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625880915/worlds01.jpg',
    'type': TYPES.BOOK,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'reading',
    'hasChapters': true,
    'paginatorIndex': 2,
    'chapterNumber': 2,
    'chapters': [
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 1', 'path': ''},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 2', 'path': ''},
      {'type': 'bullet', 'selected': true, 'comingSoon': false, 'path': 'the_war_of_the_worlds_02_01.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'the_war_of_the_worlds_02_02.json'},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 3', 'path': ''},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 4', 'path': ''},
    ]
  },
  {
    'title': 'Treasure Island - Robert Louis',
    'author': 'Robert Louis Stevenson',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625880716/trea01.jpg',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625881683/trea03.png',
    'type': TYPES.BOOK,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'reading',
    'hasChapters': true,
    'paginatorIndex': 0,
    'chapterNumber': 1,
    'chapters': [
      {'type': 'bullet', 'selected': true, 'comingSoon': false, 'path': 'treasure_island_01_part_01.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'treasure_island_01_part_02.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'treasure_island_01_part_03.json'},
      {'type': 'bullet', 'selected': false, 'comingSoon': false, 'path': 'treasure_island_01_part_04.json'},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 2', 'path': ''},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 3', 'path': ''},
      {'type': 'chapter', 'comingSoon': true, 'text': 'Chapter 4', 'path': ''},
    ]
  },
  {
    'title': 'Mark Jones',
    'author': '',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624483729/u12.jpg',
    'cover': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624483729/u12.jpg',
    'type': TYPES.READING,
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'reading',
    'path': 'mark_jones.json',
    'hasChapters': false
  },
   {
    'title': 'Describe it',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625899453/za15.jpg',    
    'type': TYPES.IMGS_HINT,
    'pack': 'pack_b',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'images',
  },
  {
    'title': "Planet's Most Jaw-Dropping Landscapes",
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624483031/u10.jpg',
    'type': TYPES.IMGS_HINT,
    'pack': 'pack_c',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'images',
    'args': {}
  },
  {
    'title': 'Morning Routine',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624481413/u03.jpg',
    'img_background': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624931186/s01.jpg',
    'img_clock': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624933828/8am02.png',
    'type': TYPES.QUIZ,
    'question_type': 'morning',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'themed_quiz',
    'header_color': 0xff6F2927
  },
  {
    'title': 'Lunchtime!',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624479597/q04.jpg',
    'img_background': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625626161/food01.png',
    'img_clock': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624933644/13pm.png',
    'type': TYPES.QUIZ,
    'question_type': 'lunch',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'themed_quiz',
    'header_color': 0xffC55A11
  },
  {
    'title': 'Day Over',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624482414/u06.png',
    'img_background': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1625626610/night01.png',
    'img_clock': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624933644/22pm.png',
    'type': TYPES.QUIZ,
    'question_type': 'night',
    'id': '1',
    'isBlocked': false,
    'price': 0,
    'nav': 'themed_quiz',
    'header_color': 0xff117D97
  },
  {
    'title': 'Day Over One',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624424883/ax05.jpg',
    'type': TYPES.QUIZ,    
    'id': '1',
    'isBlocked': true,
    'price': 200,
    'nav': 'themed_quiz',
    'args': {}
  },
  {
    'title': 'Day Over Two',
    'img': 'https://res.cloudinary.com/ddon9fx1n/image/upload/v1624424883/ax05.jpg',
    'type': TYPES.QUIZ,
    'id': '1',
    'isBlocked': true,
    'price': 200,
    'nav': 'themed_quiz',
    'args': {}
  },
];

class DataContent {
  get() {
    return _content;
  }  
}